// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonAPI.Database;

#nullable disable

namespace PokemonAPI.Migrations
{
    [DbContext(typeof(PokemonContext))]
    [Migration("20231015171013_PokemonImage")]
    partial class PokemonImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PokemonAPI.Models.Pokemon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DexNumber")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stamina")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("537a6d14-272f-4b4d-8bb5-1f53b7d9a74e"),
                            Attack = 261,
                            Defense = 175,
                            Description = "Espeon is extremely loyal to any Trainer it considers to be worthy. It is said that this Pokémon developed its precognitive powers to protect its Trainer from harm.",
                            DexNumber = 196,
                            ImageURL = "https://img.pokemondb.net/artwork/espeon.jpg",
                            Name = "Espeon",
                            Region = "Johto",
                            Stamina = 163,
                            Type = "Psychic"
                        },
                        new
                        {
                            Id = new Guid("92c13c86-63f8-41ab-a3f3-8c1d44ff4050"),
                            Attack = 126,
                            Defense = 240,
                            Description = "Umbreon evolved as a result of exposure to the moon's waves. It hides silently in darkness and waits for its foes to make a move. The rings on its body glow when it leaps to attack.",
                            DexNumber = 197,
                            ImageURL = "https://img.pokemondb.net/artwork/umbreon.jpg",
                            Name = "Umbreon",
                            Region = "Johto",
                            Stamina = 216,
                            Type = "Dark"
                        },
                        new
                        {
                            Id = new Guid("45b9a683-22d5-4e97-8f2b-9dfc1b2c362e"),
                            Attack = 171,
                            Defense = 150,
                            Description = "It's said that on nights of terrible blizzards, it comes down to human settlements. If you hear it knocking at your door, do not open it!",
                            DexNumber = 478,
                            ImageURL = "https://img.pokemondb.net/artwork/froslass.jpg",
                            Name = "Froslass",
                            Region = "Sinnoh",
                            Stamina = 172,
                            Type = "Ice/Ghost"
                        },
                        new
                        {
                            Id = new Guid("f59a62fb-9e3e-4837-8a14-0d9063b27b7d"),
                            Attack = 251,
                            Defense = 207,
                            Description = "Tyranitar is so overwhelmingly powerful, it can bring down a whole mountain to make its nest. This Pokémon wanders about in mountains seeking new opponents to fight.",
                            DexNumber = 248,
                            ImageURL = "https://img.pokemondb.net/artwork/tyranitar.jpg",
                            Name = "Tyranitar",
                            Region = "Johto",
                            Stamina = 225,
                            Type = "Rock/Dark"
                        },
                        new
                        {
                            Id = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            Attack = 275,
                            Defense = 211,
                            Description = "When Reshiram's tail flares, the heat energy moves the atmosphere and changes the world's weather.",
                            DexNumber = 643,
                            ImageURL = "https://img.pokemondb.net/artwork/reshiram.jpg",
                            Name = "Reshiram",
                            Region = "Unova",
                            Stamina = 205,
                            Type = "Dragon/Fire"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
